### ISSUE TITLE
Bot isn't removing agenda tags

### ISSUE THREAD

**Issue by astearns** [dbaron/wgmeeting-github-ircbot#40]
From the latest CSS meeting - I just noticed several (~30?) issues where we RESOLVED on things but the agenda+ tag was not removed. Example: https://github.com/w3c/csswg-drafts/issues/3264

**Comment by dbaron** [comment]
The first step to fixing this is probably to fix the "FIXME" in https://github.com/dbaron/wgmeeting-github-ircbot/blob/73a6a53cd0597b65905d3be622adfe473dbb420e/src/lib.rs#L1118-L1138 so that it reports errors properly when trying to remove labels, but only if the label is actually present.

Odds are the underlying problem is that somebody broke the bot's permissions to write to the repo, though it could be something else...

**Comment by dbaron** [comment]
OK, the bot will now report errors when removing tags, so we'll get to see what's up.

**Comment by dbaron** [comment]
The error appears to be:

> * github-bot (IRC) Successfully commented on `https://github.com/w3c/csswg-drafts/issues/4573` UNABLE TO REMOVE LABEL Agenda+ F2F on `https://github.com/w3c/csswg-drafts/issues/4573` due to `error: invalid uri character - URI(InvalidUri(InvalidUriChar))`

**Comment by dbaron** [comment]
I still need to do a bit of testing of this update before deploying it.

**Comment by dbaron** [comment]
OK, it seems like, even though all my tests pass (but the tests don't test live github or IRC interactions), I need to do the `tokio` upgrade now as well.  (And maybe `irc` too.)

<details>
<summary>The changes currently cause panics with the following:</summary>

```
[2020-07-17T06:08:56Z INFO  wgmeeting_github_ircbot] [#cssbottest] <dbaron> Topic: testing following hubcaps upgrade
[2020-07-17T06:09:00Z INFO  wgmeeting_github_ircbot] [#cssbottest] <dbaron> github: https://github.com/dbaron/wgmeeting-github-ircbot/issues/40
thread 'main' panicked at 'not currently running on the Tokio runtime.', /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/handle.rs:106:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:486
  11: rust_begin_unwind
             at src/libstd/panicking.rs:388
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:101
  13: core::option::expect_failed
             at src/libcore/option.rs:1264
  14: core::option::Option<T>::expect
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libcore/option.rs:349
  15: tokio::runtime::handle::Handle::current
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/handle.rs:106
  16: tokio::runtime::blocking::pool::spawn_blocking
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/blocking/pool.rs:65
  17: tokio::task::blocking::spawn_blocking
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/task/blocking.rs:117
  18: <hyper::client::connect::dns::GaiResolver as tower_service::Service<hyper::client::connect::dns::Name>>::call
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.7/src/client/connect/dns.rs:120
  19: <S as hyper::client::connect::dns::sealed::Resolve>::resolve
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.7/src/client/connect/dns.rs:338
  20: hyper::client::connect::dns::resolve::{{closure}}
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.7/src/client/connect/dns.rs:348
  21: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libcore/future/mod.rs:73
  22: hyper::client::connect::http::HttpConnector<R>::call_async::{{closure}}
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.7/src/client/connect/http.rs:306
  23: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libcore/future/mod.rs:73
  24: <hyper::client::connect::http::HttpConnector<R> as tower_service::Service<http::uri::Uri>>::call::{{closure}}
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.7/src/client/connect/http.rs:247
  25: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libcore/future/mod.rs:73
  26: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libcore/future/future.rs:118
  27: <hyper::client::connect::http::HttpConnecting<R> as core::future::future::Future>::poll
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.7/src/client/connect/http.rs:387
  28: <futures_util::future::either::Either<A,B> as core::future::future::Future>::poll
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.5/src/future/either.rs:65
  29: <hyper_tls::client::HttpsConnector<T> as tower_service::Service<http::uri::Uri>>::call::{{closure}}
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-tls-0.4.3/src/client.rs:127
  30: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libcore/future/mod.rs:73
  31: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libcore/future/future.rs:118
  32: <hyper_tls::client::HttpsConnecting<T> as core::future::future::Future>::poll
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-tls-0.4.3/src/client.rs:156
  33: reqwest::connect::Connector::connect_with_maybe_proxy::{{closure}}
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.10.6/src/connect.rs:346
  34: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libcore/future/mod.rs:73
  35: reqwest::connect::with_timeout::{{closure}}
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.10.6/src/connect.rs:500
  36: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libcore/future/mod.rs:73
  37: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libcore/future/future.rs:118
  38: <hyper::service::oneshot::Oneshot<S,Req> as core::future::future::Future>::poll
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.7/src/service/oneshot.rs:50
  39: <F as futures_core::future::TryFuture>::try_poll
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.5/src/future.rs:83
  40: <futures_util::future::try_future::into_future::IntoFuture<Fut> as core::future::future::Future>::poll
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.5/src/future/try_future/into_future.rs:31
  41: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.5/src/future/future/map.rs:67
  42: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.5/src/lib.rs:107
  43: <futures_util::future::try_future::MapErr<Fut,F> as core::future::future::Future>::poll
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.5/src/lib.rs:107
  44: <F as futures_core::future::TryFuture>::try_poll
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.5/src/future.rs:83
  45: <futures_util::future::try_future::into_future::IntoFuture<Fut> as core::future::future::Future>::poll
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.5/src/future/try_future/into_future.rs:31
  46: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.5/src/future/future/map.rs:67
  47: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.5/src/lib.rs:107
  48: <futures_util::future::try_future::MapOk<Fut,F> as core::future::future::Future>::poll
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.5/src/lib.rs:107
  49: <F as futures_core::future::TryFuture>::try_poll
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.5/src/future.rs:83
  50: <futures_util::future::try_future::try_flatten::TryFlatten<Fut,<Fut as futures_core::future::TryFuture>::Ok> as core::future::future::Future>::poll
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.5/src/future/try_future/try_flatten.rs:47
  51: <futures_util::future::try_future::TryFlatten<Fut1,Fut2> as core::future::future::Future>::poll
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.5/src/lib.rs:107
  52: <futures_util::future::try_future::AndThen<Fut1,Fut2,F> as core::future::future::Future>::poll
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.5/src/lib.rs:107
  53: <futures_util::future::either::Either<A,B> as core::future::future::Future>::poll
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.5/src/future/either.rs:65
  54: <hyper::common::lazy::Lazy<F,R> as core::future::future::Future>::poll
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.7/src/common/lazy.rs:59
  55: futures_util::future::future::FutureExt::poll_unpin
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.5/src/future/future/mod.rs:554
  56: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.5/src/future/select.rs:64
  57: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.5/src/future/future/map.rs:67
  58: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.5/src/lib.rs:107
  59: <futures_util::future::future::flatten::Flatten<Fut,<Fut as core::future::future::Future>::Output> as core::future::future::Future>::poll
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.5/src/future/future/flatten.rs:47
  60: <futures_util::future::future::Then<Fut1,Fut2,F> as core::future::future::Future>::poll
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.5/src/lib.rs:107
  61: <F as futures_core::future::TryFuture>::try_poll
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.5/src/future.rs:83
  62: <futures_util::future::try_future::into_future::IntoFuture<Fut> as core::future::future::Future>::poll
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.5/src/future/try_future/into_future.rs:31
  63: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.5/src/future/future/map.rs:67
  64: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.5/src/lib.rs:107
  65: <futures_util::future::try_future::MapOk<Fut,F> as core::future::future::Future>::poll
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.5/src/lib.rs:107
  66: <F as futures_core::future::TryFuture>::try_poll
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.5/src/future.rs:83
  67: <futures_util::future::try_future::try_flatten::TryFlatten<Fut,<Fut as futures_core::future::TryFuture>::Ok> as core::future::future::Future>::poll
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.5/src/future/try_future/try_flatten.rs:47
  68: <futures_util::future::try_future::TryFlatten<Fut1,Fut2> as core::future::future::Future>::poll
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.5/src/lib.rs:107
  69: <futures_util::future::try_future::AndThen<Fut1,Fut2,F> as core::future::future::Future>::poll
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.5/src/lib.rs:107
  70: hyper::client::Client<C,B>::retryably_send_request::{{closure}}
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.7/src/client/mod.rs:255
  71: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.5/src/future/poll_fn.rs:54
  72: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libcore/future/future.rs:118
  73: <hyper::client::ResponseFuture as core::future::future::Future>::poll
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.7/src/client/mod.rs:627
  74: <reqwest::async_impl::client::PendingRequest as core::future::future::Future>::poll
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.10.6/src/async_impl/client.rs:1321
  75: <reqwest::async_impl::client::Pending as core::future::future::Future>::poll
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.10.6/src/async_impl/client.rs:1300
  76: <F as futures_core::future::TryFuture>::try_poll
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.5/src/future.rs:83
  77: <futures_util::future::try_future::into_future::IntoFuture<Fut> as core::future::future::Future>::poll
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.5/src/future/try_future/into_future.rs:31
  78: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.5/src/future/future/map.rs:67
  79: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.5/src/lib.rs:107
  80: <futures_util::future::try_future::MapErr<Fut,F> as core::future::future::Future>::poll
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.5/src/lib.rs:107
  81: <F as futures_core::future::TryFuture>::try_poll
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.5/src/future.rs:83
  82: <futures_util::future::try_future::try_flatten::TryFlatten<Fut,<Fut as futures_core::future::TryFuture>::Ok> as core::future::future::Future>::poll
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.5/src/future/try_future/try_flatten.rs:56
  83: <futures_util::future::try_future::TryFlatten<Fut1,Fut2> as core::future::future::Future>::poll
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.5/src/lib.rs:107
  84: <futures_util::future::try_future::AndThen<Fut1,Fut2,F> as core::future::future::Future>::poll
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.5/src/lib.rs:107
  85: <F as futures_core::future::TryFuture>::try_poll
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.5/src/future.rs:83
  86: <futures_util::future::try_future::into_future::IntoFuture<Fut> as core::future::future::Future>::poll
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.5/src/future/try_future/into_future.rs:31
  87: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.5/src/future/future/map.rs:67
  88: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.5/src/lib.rs:107
  89: <futures_util::future::try_future::MapOk<Fut,F> as core::future::future::Future>::poll
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.5/src/lib.rs:107
  90: <F as futures_core::future::TryFuture>::try_poll
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.5/src/future.rs:83
  91: <futures_util::future::try_future::try_flatten::TryFlatten<Fut,<Fut as futures_core::future::TryFuture>::Ok> as core::future::future::Future>::poll
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.5/src/future/try_future/try_flatten.rs:47
  92: <futures_util::future::try_future::TryFlatten<Fut1,Fut2> as core::future::future::Future>::poll
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.5/src/lib.rs:107
  93: <futures_util::future::try_future::AndThen<Fut1,Fut2,F> as core::future::future::Future>::poll
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.5/src/lib.rs:107
  94: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libcore/future/future.rs:118
  95: <F as futures_core::future::TryFuture>::try_poll
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.5/src/future.rs:83
  96: <futures_util::future::try_future::into_future::IntoFuture<Fut> as core::future::future::Future>::poll
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.5/src/future/try_future/into_future.rs:31
  97: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.5/src/future/future/map.rs:67
  98: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.5/src/lib.rs:107
  99: <futures_util::future::try_future::MapOk<Fut,F> as core::future::future::Future>::poll
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.5/src/lib.rs:107
 100: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libcore/future/future.rs:118
 101: <F as futures_core::future::TryFuture>::try_poll
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.5/src/future.rs:83
 102: <futures_util::future::try_future::into_future::IntoFuture<Fut> as core::future::future::Future>::poll
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.5/src/future/try_future/into_future.rs:31
 103: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.5/src/future/future/map.rs:67
 104: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.5/src/lib.rs:107
 105: <futures_util::future::try_future::MapOk<Fut,F> as core::future::future::Future>::poll
             at /home/dbaron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.5/src/lib.rs:107
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</summary>

**Comment by dbaron** [comment]
The bot is now deployed with this fix.

I ended up having to update all the core dependencies at the same time (both the github library and the irc library) because of their ties to API changes in futures and tokio, but now I'm fully on [futures](https://docs.rs/futures/) 0.3 and [tokio 0.2](https://tokio.rs/blog/2019-11-tokio-0-2/), which is good.  That should in turn let me do a bit of other code cleanup and modernization.
